// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWin.Infrastructure.Data;

#nullable disable

namespace StarWin.Web.Data.Migrations
{
    [DbContext(typeof(StarWinDbContext))]
    partial class StarWinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.AlienRace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AppearanceType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("BodyChemistry")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BodyCoverType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("Devotion")
                        .HasColumnType("tinyint");

                    b.Property<string>("DevotionLevel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("GovernmentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("HomePlanetId")
                        .HasColumnType("int");

                    b.Property<byte[]>("LegacyAttributes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("LimbPairCount")
                        .HasColumnType("tinyint");

                    b.Property<short>("MassKg")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Reproduction")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ReproductionMethod")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<short>("SizeCm")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("AlienRaces", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.Colony", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte>("AgeCenturies")
                        .HasColumnType("tinyint");

                    b.Property<int>("AllegianceId")
                        .HasColumnType("int");

                    b.Property<string>("AllegianceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ColonistRaceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ColonyClass")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte>("ColonyClassCode")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ControllingEmpireId")
                        .HasColumnType("int");

                    b.Property<byte>("Crime")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EncodedPopulation")
                        .HasColumnType("tinyint");

                    b.Property<long>("EstimatedPopulation")
                        .HasColumnType("bigint");

                    b.Property<string>("ExportResource")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("ExportResourceCode")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FoundingEmpireId")
                        .HasColumnType("int");

                    b.Property<string>("GovernmentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("GovernmentTypeCode")
                        .HasColumnType("tinyint");

                    b.Property<int>("GrossWorldProductMcr")
                        .HasColumnType("int");

                    b.Property<string>("ImportResource")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte>("ImportResourceCode")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Law")
                        .HasColumnType("tinyint");

                    b.Property<int>("MilitaryPower")
                        .HasColumnType("int");

                    b.Property<byte>("NativePopulationPercent")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ParentEmpireId")
                        .HasColumnType("int");

                    b.Property<string>("PoliticalStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<byte>("Stability")
                        .HasColumnType("tinyint");

                    b.Property<string>("Starport")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte>("StarportCode")
                        .HasColumnType("tinyint");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.Property<string>("WorldKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("WorldId")
                        .IsUnique();

                    b.ToTable("Colonies", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.ColonyDemographic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColonyId")
                        .HasColumnType("int");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PopulationPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("ColonyId");

                    b.ToTable("ColonyDemographics", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.Empire", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CaptivePlanets")
                        .HasColumnType("int");

                    b.Property<long>("CaptivePopulationMillions")
                        .HasColumnType("bigint");

                    b.Property<long>("EconomicPowerMcr")
                        .HasColumnType("bigint");

                    b.Property<string>("ExpansionPolicy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("IndependentColonies")
                        .HasColumnType("int");

                    b.Property<long>("IndependentPopulationMillions")
                        .HasColumnType("bigint");

                    b.Property<int?>("LegacyRaceId")
                        .HasColumnType("int");

                    b.Property<long>("MilitaryPower")
                        .HasColumnType("bigint");

                    b.Property<int>("Moons")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long>("NativePopulationMillions")
                        .HasColumnType("bigint");

                    b.Property<int>("Planets")
                        .HasColumnType("int");

                    b.Property<int>("SpaceHabitats")
                        .HasColumnType("int");

                    b.Property<long>("SubjectPopulationMillions")
                        .HasColumnType("bigint");

                    b.Property<int>("SubjugatedMoons")
                        .HasColumnType("int");

                    b.Property<int>("SubjugatedPlanets")
                        .HasColumnType("int");

                    b.Property<long>("TradeBonusMcr")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Empires", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.EmpireContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<int>("EmpireId")
                        .HasColumnType("int");

                    b.Property<int>("OtherEmpireId")
                        .HasColumnType("int");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte>("RelationCode")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("EmpireId");

                    b.ToTable("EmpireContacts", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.EmpireRaceMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpireId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<long>("PopulationMillions")
                        .HasColumnType("bigint");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("EmpireId");

                    b.ToTable("EmpireRaceMemberships", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.HistoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Century")
                        .HasColumnType("int");

                    b.Property<int?>("ColonyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<int?>("EmpireId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("OtherRaceId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<int?>("StarSystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("HistoryEvents", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Media.EntityImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TargetKind", "TargetId");

                    b.ToTable("EntityImages", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.AstralBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte>("ClassificationCode")
                        .HasColumnType("tinyint");

                    b.Property<double?>("CompanionOrbitAu")
                        .HasColumnType("float");

                    b.Property<byte>("DecimalClassCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double?>("Luminosity")
                        .HasColumnType("float");

                    b.Property<byte>("PlanetCount")
                        .HasColumnType("tinyint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double?>("SolarMasses")
                        .HasColumnType("float");

                    b.Property<int?>("StarSystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarSystemId");

                    b.ToTable("AstralBodies", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.SectorConfiguration", b =>
                {
                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasicHyperlaneMaximumLengthParsecs")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("BasicHyperlaneTierName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("SectorId");

                    b.ToTable("SectorConfigurations", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.SpaceHabitat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("BuiltByEmpireId")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructedCentury")
                        .HasColumnType("int");

                    b.Property<int?>("ControlledByEmpireId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<double?>("OrbitRadiusKm")
                        .HasColumnType("float");

                    b.Property<int>("OrbitTargetId")
                        .HasColumnType("int");

                    b.Property<string>("OrbitTargetKind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<int?>("StarSystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StarSystemId");

                    b.ToTable("SpaceHabitats", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.StarSystem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AllegianceId")
                        .HasColumnType("int");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<int?>("LegacySystemId")
                        .HasColumnType("int");

                    b.Property<byte>("MapCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId", "LegacySystemId");

                    b.HasIndex("SectorId", "Name");

                    b.ToTable("StarSystems", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.StarWinSector", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.UnusualCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Code")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Notes")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int?>("WorldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("UnusualCharacteristics", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.World", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double?>("Albedo")
                        .HasColumnType("float");

                    b.Property<int?>("AlienRaceId")
                        .HasColumnType("int");

                    b.Property<int>("AllegianceId")
                        .HasColumnType("int");

                    b.Property<string>("AtmosphereComposition")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("AtmosphereType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<float>("AtmosphericPressure")
                        .HasColumnType("real");

                    b.Property<short>("AverageTemperatureCelsius")
                        .HasColumnType("smallint");

                    b.Property<byte?>("AxialTiltDegrees")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BoilingPointCelsius")
                        .HasColumnType("int");

                    b.Property<int?>("ControlledByEmpireId")
                        .HasColumnType("int");

                    b.Property<byte>("DensityTenthsEarth")
                        .HasColumnType("tinyint");

                    b.Property<int>("DiameterKm")
                        .HasColumnType("int");

                    b.Property<int?>("EccentricityThousandths")
                        .HasColumnType("int");

                    b.Property<double?>("EscapeVelocityKmPerSecond")
                        .HasColumnType("float");

                    b.Property<double?>("GravityEarthG")
                        .HasColumnType("float");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("LegacyMoonId")
                        .HasColumnType("int");

                    b.Property<int?>("LegacyPlanetId")
                        .HasColumnType("int");

                    b.Property<double?>("MagneticFieldGauss")
                        .HasColumnType("float");

                    b.Property<double?>("MassEarthMasses")
                        .HasColumnType("float");

                    b.Property<byte>("MiscellaneousFlags")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<double?>("OrbitPeriodDays")
                        .HasColumnType("float");

                    b.Property<double?>("OrbitRadiusAu")
                        .HasColumnType("float");

                    b.Property<double?>("OrbitRadiusKm")
                        .HasColumnType("float");

                    b.Property<byte?>("OrbitalInclinationDegrees")
                        .HasColumnType("tinyint");

                    b.Property<double?>("OxygenPressureAtmospheres")
                        .HasColumnType("float");

                    b.Property<int?>("ParentWorldId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryAstralBodySequence")
                        .HasColumnType("int");

                    b.Property<long?>("RotationPeriodHours")
                        .HasColumnType("bigint");

                    b.Property<byte?>("SmallestMolecularWeightRetained")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StarSystemId")
                        .HasColumnType("int");

                    b.Property<string>("WaterType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("WorldType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("StarSystemId", "LegacyMoonId");

                    b.HasIndex("StarSystemId", "LegacyPlanetId");

                    b.ToTable("Worlds", (string)null);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.AlienRace", b =>
                {
                    b.OwnsOne("StarWin.Domain.Model.Entity.Civilization.AlienBiologyProfile", "BiologyProfile", b1 =>
                        {
                            b1.Property<int>("AlienRaceId")
                                .HasColumnType("int");

                            b1.Property<byte>("Body")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Lifespan")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Mind")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("PsiPower")
                                .HasColumnType("tinyint");

                            b1.Property<string>("PsiRating")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<byte>("Speed")
                                .HasColumnType("tinyint");

                            b1.HasKey("AlienRaceId");

                            b1.ToTable("AlienRaces");

                            b1.WithOwner()
                                .HasForeignKey("AlienRaceId");
                        });

                    b.Navigation("BiologyProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.Colony", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.World", null)
                        .WithOne("Colony")
                        .HasForeignKey("StarWin.Domain.Model.Entity.Civilization.Colony", "WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.ColonyDemographic", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.Civilization.Colony", null)
                        .WithMany("Demographics")
                        .HasForeignKey("ColonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.Empire", b =>
                {
                    b.OwnsOne("StarWin.Domain.Model.Entity.Civilization.CivilizationProfile", "CivilizationProfile", b1 =>
                        {
                            b1.Property<int>("EmpireId")
                                .HasColumnType("int");

                            b1.Property<byte>("Art")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Determination")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Individualism")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Loyalty")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Militancy")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("Progressiveness")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("RacialTolerance")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("SocialCohesion")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("SpatialAge")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("TechLevel")
                                .HasColumnType("tinyint");

                            b1.HasKey("EmpireId");

                            b1.ToTable("Empires");

                            b1.WithOwner()
                                .HasForeignKey("EmpireId");
                        });

                    b.OwnsOne("StarWin.Domain.Model.Entity.Civilization.EmpireFounding", "Founding", b1 =>
                        {
                            b1.Property<int>("EmpireId")
                                .HasColumnType("int");

                            b1.Property<int?>("FoundedCentury")
                                .HasColumnType("int");

                            b1.Property<int?>("FoundingColonyId")
                                .HasColumnType("int");

                            b1.Property<int?>("FoundingRaceId")
                                .HasColumnType("int");

                            b1.Property<int?>("FoundingWorldId")
                                .HasColumnType("int");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.Property<int?>("ParentEmpireId")
                                .HasColumnType("int");

                            b1.HasKey("EmpireId");

                            b1.ToTable("Empires");

                            b1.WithOwner()
                                .HasForeignKey("EmpireId");
                        });

                    b.OwnsOne("StarWin.Domain.Model.Entity.Military.MilitaryForceProfile", "MilitaryForces", b1 =>
                        {
                            b1.Property<int>("EmpireId")
                                .HasColumnType("int");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1200)
                                .HasColumnType("nvarchar(1200)");

                            b1.HasKey("EmpireId");

                            b1.ToTable("Empires");

                            b1.WithOwner()
                                .HasForeignKey("EmpireId");

                            b1.OwnsMany("StarWin.Domain.Model.Entity.Military.GroundForceGroup", "GroundForces", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("MilitaryForceProfileEmpireId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MilitaryForceProfileEmpireId");

                                    b2.ToTable("EmpireGroundForces", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MilitaryForceProfileEmpireId");
                                });

                            b1.OwnsMany("StarWin.Domain.Model.Entity.Military.MilitaryInstallationGroup", "Bases", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)");

                                    b2.Property<int>("MilitaryForceProfileEmpireId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MilitaryForceProfileEmpireId");

                                    b2.ToTable("EmpireMilitaryBases", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MilitaryForceProfileEmpireId");
                                });

                            b1.OwnsOne("StarWin.Domain.Model.Entity.Military.MilitaryPersonnelProfile", "Personnel", b2 =>
                                {
                                    b2.Property<int>("MilitaryForceProfileEmpireId")
                                        .HasColumnType("int");

                                    b2.Property<string>("ConscriptionPolicy")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.Property<string>("CrewQuality")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.Property<byte>("CrewRating")
                                        .HasColumnType("tinyint");

                                    b2.Property<string>("TroopQuality")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.Property<byte>("TroopRating")
                                        .HasColumnType("tinyint");

                                    b2.HasKey("MilitaryForceProfileEmpireId");

                                    b2.ToTable("Empires");

                                    b2.WithOwner()
                                        .HasForeignKey("MilitaryForceProfileEmpireId");
                                });

                            b1.OwnsOne("StarWin.Domain.Model.Entity.Military.NavyDoctrine", "NavyDoctrine", b2 =>
                                {
                                    b2.Property<int>("MilitaryForceProfileEmpireId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("AssaultEmphasisPercent")
                                        .HasColumnType("tinyint");

                                    b2.Property<byte>("BeamWeaponEmphasisPercent")
                                        .HasColumnType("tinyint");

                                    b2.Property<byte>("DefenseEmphasisPercent")
                                        .HasColumnType("tinyint");

                                    b2.Property<byte>("FighterEmphasisPercent")
                                        .HasColumnType("tinyint");

                                    b2.Property<byte>("MissileEmphasisPercent")
                                        .HasColumnType("tinyint");

                                    b2.HasKey("MilitaryForceProfileEmpireId");

                                    b2.ToTable("Empires");

                                    b2.WithOwner()
                                        .HasForeignKey("MilitaryForceProfileEmpireId");
                                });

                            b1.OwnsMany("StarWin.Domain.Model.Entity.Military.StarshipGroup", "Fleet", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Class")
                                        .IsRequired()
                                        .HasMaxLength(80)
                                        .HasColumnType("nvarchar(80)");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("nvarchar(16)");

                                    b2.Property<int>("MilitaryForceProfileEmpireId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("nvarchar(120)");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MilitaryForceProfileEmpireId");

                                    b2.ToTable("EmpireFleet", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("MilitaryForceProfileEmpireId");
                                });

                            b1.Navigation("Bases");

                            b1.Navigation("Fleet");

                            b1.Navigation("GroundForces");

                            b1.Navigation("NavyDoctrine")
                                .IsRequired();

                            b1.Navigation("Personnel")
                                .IsRequired();
                        });

                    b.Navigation("CivilizationProfile")
                        .IsRequired();

                    b.Navigation("Founding")
                        .IsRequired();

                    b.Navigation("MilitaryForces")
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.EmpireContact", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.Civilization.Empire", null)
                        .WithMany("Contacts")
                        .HasForeignKey("EmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.EmpireRaceMembership", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.Civilization.Empire", null)
                        .WithMany("RaceMemberships")
                        .HasForeignKey("EmpireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.HistoryEvent", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.StarWinSector", null)
                        .WithMany("History")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.AstralBody", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.StarSystem", null)
                        .WithMany("AstralBodies")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.SectorConfiguration", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.StarWinSector", null)
                        .WithOne("Configuration")
                        .HasForeignKey("StarWin.Domain.Model.Entity.StarMap.SectorConfiguration", "SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.SpaceHabitat", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.StarSystem", null)
                        .WithMany("SpaceHabitats")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.StarSystem", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.StarWinSector", null)
                        .WithMany("Systems")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.UnusualCharacteristic", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.World", null)
                        .WithMany("UnusualCharacteristics")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.World", b =>
                {
                    b.HasOne("StarWin.Domain.Model.Entity.StarMap.StarSystem", null)
                        .WithMany("Worlds")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("StarWin.Domain.Model.Entity.StarMap.Hydrography", "Hydrography", b1 =>
                        {
                            b1.Property<int>("WorldId")
                                .HasColumnType("int");

                            b1.Property<byte>("CloudPercent")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("IcePercent")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("WaterPercent")
                                .HasColumnType("tinyint");

                            b1.HasKey("WorldId");

                            b1.ToTable("Worlds");

                            b1.WithOwner()
                                .HasForeignKey("WorldId");
                        });

                    b.OwnsOne("StarWin.Domain.Model.Entity.StarMap.MineralResources", "MineralResources", b1 =>
                        {
                            b1.Property<int>("WorldId")
                                .HasColumnType("int");

                            b1.Property<byte>("MetalOre")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("PreciousGems")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("PreciousMetal")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("RadioactiveOre")
                                .HasColumnType("tinyint");

                            b1.Property<byte>("RawCrystals")
                                .HasColumnType("tinyint");

                            b1.HasKey("WorldId");

                            b1.ToTable("Worlds");

                            b1.WithOwner()
                                .HasForeignKey("WorldId");
                        });

                    b.Navigation("Hydrography")
                        .IsRequired();

                    b.Navigation("MineralResources")
                        .IsRequired();
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.Colony", b =>
                {
                    b.Navigation("Demographics");
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.Civilization.Empire", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("RaceMemberships");
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.StarSystem", b =>
                {
                    b.Navigation("AstralBodies");

                    b.Navigation("SpaceHabitats");

                    b.Navigation("Worlds");
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.StarWinSector", b =>
                {
                    b.Navigation("Configuration")
                        .IsRequired();

                    b.Navigation("History");

                    b.Navigation("Systems");
                });

            modelBuilder.Entity("StarWin.Domain.Model.Entity.StarMap.World", b =>
                {
                    b.Navigation("Colony");

                    b.Navigation("UnusualCharacteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
